---
- name: Install ClickHouse, Vector and Lighthouse
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

  roles:
    - clickhouse
    - vector-role
    - lighthouse-role
